require: 
  - rubocop-performance
  - rubocop-rspec

# Default RuboCop settings.
AllCops:
  TargetRubyVersion: 2.7
  DefaultFormatter: fuubar
  DisplayCopNames: true
  ExtraDetails: true
  Exclude:
    - rakelib/**/*.rake
  RSpec:
    Patterns:
      - '_spec.rb$'

Metrics/BlockLength:
  Exclude:
  - '**/*_spec.rb'
  - '**/spec/**/*.rb'
  - '**/rakelib/**/*.rake'
  - '**/*.gemspec'

Metrics/MethodLength:
  Exclude:
  - rakelib/**/*.rake
  - lib/rake/**.rb
  - '**/spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
  - spec/**/*.rb

Metrics/AbcSize:
  Exclude:
  - rakelib/**/*.rake
  - '**/spec/**/*.rb'

Metrics/LineLength:
  Max: 80

Style/Encoding:
  StyleGuide: '#utf-8'
  Enabled: true

Style/Documentation:
  Enabled: false
